[package]
name = "xhci"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "xHCI USB Controller Driver for LevitateOS"

[dependencies]
input-device = { path = "../../traits/input-device" }
los_error = { path = "../../kernel/lib/error" }
log = "0.4"
