[package]
name = "xhci"
version = "0.1.0"
edition = "2024"
readme = "README.md"
description = "xHCI USB Controller Driver for LevitateOS"

[dependencies]
los_traits = { path = "../../traits" }
los_error = { path = "../../error" }
log = "0.4"
