[package]
name = "repro_crash"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lints]
workspace = true

[[bin]]
name = "repro"
path = "src/main.rs"

[dependencies]
libsyscall = { path = "../libsyscall" }
