[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
panic = "abort"
lto = false
opt-level = 1

# Keep this package out of the kernel workspace
[workspace]

# Build for bare-metal AArch64
[build]
target = "aarch64-unknown-none"

